### ISSUE TITLE
Match also the names

### ISSUE THREAD

**Issue by raine** [goronfreeman/alfred-http-status-codes#2]
I'd appreciate if `http inter` would also work and match `500 Internal Server Error`

Because sometimes it's the code I don't remember and need to search by the name.

**Comment by goronfreeman** [comment]
Would you prefer it to match just the beginning of the status code name, or to search anywhere in the status code name?

**Comment by raine** [comment]
I think searching anywhere in case-insensitive manner would be best.

**Comment by goronfreeman** [comment]
Added in the [latest release](https://github.com/goronfreeman/alfred-http-status-codes/releases/tag/v1.1). Thanks for the suggestion.

**Comment by goronfreeman** [comment]
Added in the [latest release](https://github.com/goronfreeman/alfred-http-status-codes/releases/tag/v1.1). Thanks for the suggestion.

**Comment by raine** [comment]
Great stuff. Do you think just typing `http` or `http<space>` should list all codes?

**Comment by goronfreeman** [comment]
If it's something you would personally find useful, feel free to open an issue, and I'll get to it when I can. Thanks.
