### ISSUE TITLE
Project mascot suggestion

### ISSUE THREAD

**Issue by bruschill** [goronfreeman/alfred-http-status-codes#3]
![shine](https://cloud.githubusercontent.com/assets/621389/7967722/b7bab872-09e0-11e5-88fb-895952947769.png)

**Comment by bruschill** [comment]
+1

**Comment by konapun** [comment]
![status-codes](https://cloud.githubusercontent.com/assets/498643/7970023/cd2f676e-0a00-11e5-9597-627feafe931a.png)

Proposal for official logo

**Comment by bruschill** [comment]
The version from @konapun should be chosen.

+2

**Comment by goronfreeman** [comment]
Issue resolved in latest README.
